# fly.toml file generated for cargo-quickinstall-stats-server on 2023-03-04T20:27:42Z

app = "cargo-quickinstall-stats-server"
kill_signal = "SIGINT"
kill_timeout = 5
deploy.strategy = "bluegreen"

[env]
  PORT = "8080"
  # Run `fly deploy --env KEY=VALUE` to override any of these.
  # INFLUX_TOKEN is provided as a secret.
  INFLUX_URL='https://us-east-1-1.aws.cloud2.influxdata.com'
  INFLUX_ORG = "cargo-bins"
  INFLUX_BUCKET = "cargo-quickinstall"


[[services]]
  internal_port = 8080
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    port = "8080"
    restart_limit = 6
    timeout = "2s"
