[package]
name = "cargo-quickinstall"
version = "0.2.3"
authors = ["David Laban <david.laban@red-badger.com>"]
edition = "2018"
description = "Precompiled binary installs for `cargo install`"
license = "MIT OR Apache-2.0"
readme = "../README.md"
repository = "https://github.com/alsuren/cargo-quickinstall"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tinyjson = "2"
home = "0.5.3"
pico-args = "0.4.2"
