name: Fly Deploy
on:
  push:
    branches:
      - main
    paths:
      - 'stats-server'

jobs:
  deploy:
    name: Deploy app
    environment: stats server production
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v6
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy stats-server --wait-timeout 1m
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
